POST http://192.167.110.31/calc_MagneticDeclination HTTP/1.1
Content-Type: application/json

{
    "lat":31.2304,
	"lon":121.4737,
	"alt":0.0,
	"year":2025.3
}


POST http://192.167.110.31/set_RA_DEC_HDMS HTTP/1.1
content-type: application/json

{
	"ra_h":3,
	"ra_m":33,
	"ra_s":33,
	"dec_d":75,
	"dec_m":25,
	"dec_s":45
}
